# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 014d9ca01d533e9aecf3fbd4ff271b4d4ec494a01c7d1f293259c3b87730a61b55cf098dbcb85c635e872faa8322894a32a9064033dbf8aa73c69bc746be07d7

test:
  secret_key_base: 28564fad8e8c23082863acc1956e86ff8ee2ace92e9becbd99f28892a23d6d143252dfdeafbcc3755d21224be978e5d608c265715924166b4499c8b4060d8d70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
